/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coba;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class CatatanPasien extends javax.swing.JFrame {

    public int flag = 0;

    /**
     * Creates new form CatatanPasien
     */
    public CatatanPasien() {
        initComponents();
        LabelPilihJenisKamar.setVisible(false);
        cbJenisKamar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputGejala = new javax.swing.JTextField();
        LabelPilihJenisKamar = new javax.swing.JLabel();
        cbJenisKamar = new javax.swing.JComboBox<>();
        btnInfoKamar = new javax.swing.JButton();
        inputDiagnosis = new javax.swing.JTextField();
        inputObat = new javax.swing.JTextField();
        inputIDPasien = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CBYes = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("ID Pasien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 67, 112, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1036, 67, 144, 34));

        Tabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.setAutoscrolls(false);
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 137, 1076, 88));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Gejala");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 272, 63, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Diagnosis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 336, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Obat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 398, -1, -1));

        inputGejala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(inputGejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 269, 310, -1));

        LabelPilihJenisKamar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelPilihJenisKamar.setForeground(new java.awt.Color(51, 102, 255));
        LabelPilihJenisKamar.setText("Kamar");
        getContentPane().add(LabelPilihJenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 337, 63, -1));

        cbJenisKamar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbJenisKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kamar", "-", "Umum", "Kelas II", "Kelas I", "VIP/VVIP" }));
        getContentPane().add(cbJenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 336, 271, -1));

        btnInfoKamar.setBackground(new java.awt.Color(255, 255, 255));
        btnInfoKamar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInfoKamar.setForeground(new java.awt.Color(51, 102, 255));
        btnInfoKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/Icon Kamar.png"))); // NOI18N
        btnInfoKamar.setText("Informasi Kamar");
        btnInfoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoKamarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 394, -1, -1));

        inputDiagnosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(inputDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 333, 310, -1));

        inputObat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(inputObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 395, 310, -1));

        inputIDPasien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(inputIDPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 70, 775, -1));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(51, 102, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/Add Icon.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setMaximumSize(new java.awt.Dimension(140, 50));
        btnSimpan.setMinimumSize(new java.awt.Dimension(140, 50));
        btnSimpan.setPreferredSize(new java.awt.Dimension(140, 50));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 529, -1, -1));

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(51, 102, 255));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/Back Button.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setMaximumSize(new java.awt.Dimension(140, 50));
        btnKembali.setMinimumSize(new java.awt.Dimension(140, 50));
        btnKembali.setPreferredSize(new java.awt.Dimension(140, 50));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 529, 178, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Apakah perlu rawat inap?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 271, 250, -1));

        CBYes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CBYes.setForeground(new java.awt.Color(51, 102, 255));
        CBYes.setText("Ya");
        CBYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBYesActionPerformed(evt);
            }
        });
        getContentPane().add(CBYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 269, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1180, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/BgCatatanPasien.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginDokter loginD = new LoginDokter();
        loginD.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            String idPasien = inputIDPasien.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT ID_Pasien, Nama, Usia, Jenis_Kelamin, Status_Hubungan, Alamat, Telp, Golongan_Darah, Tanggal_Periksa, Riwayat_Penyakit FROM datapasien where ID_Pasien = '"+idPasien+"'");
            ResultSet rs = pst.executeQuery();
            Tabel.setModel(DbUtils.resultSetToTableModel(rs));
            if (!rs.isFirst()) {
                inputIDPasien.setEditable(true);
                flag = 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (flag == 1) {
            String idPasien = inputIDPasien.getText();
            String gejala = inputGejala.getText();
            String diagnosis = inputDiagnosis.getText();
            String obat = inputObat.getText();
            String jeniskamar;
            String rawatinap;

            if (CBYes.isSelected()) {
                rawatinap = "YES";
                jeniskamar = (String) cbJenisKamar.getSelectedItem();
            } else {
                rawatinap = "NO";
                jeniskamar = "";
            }
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select ID_Pasien, Nama, Usia, Jenis_Kelamin, Status_Hubungan, Alamat, Telp, Golongan_Darah, Tanggal_Periksa, Riwayat_Penyakit from datapasien where ID_Pasien = '" +inputIDPasien+"'");
                if (!rs.isBeforeFirst()) {
                    st.executeUpdate("insert into catatandokter values('"+idPasien+"','" +gejala+ "','"+diagnosis+ "','"+obat+ "','" +jeniskamar+"')");
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ada!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID Pasien kosong!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void CBYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBYesActionPerformed
        // TODO add your handling code here:
        if (CBYes.isSelected()) {
            LabelPilihJenisKamar.setVisible(true);
            cbJenisKamar.setVisible(true);
        } else {
            LabelPilihJenisKamar.setVisible(false);
            cbJenisKamar.setVisible(false);
        }
    }//GEN-LAST:event_CBYesActionPerformed

    private void btnInfoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoKamarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InfoKamar info = new InfoKamar();
        info.setVisible(true);
    }//GEN-LAST:event_btnInfoKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatatanPasien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatatanPasien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatatanPasien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatatanPasien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatatanPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBYes;
    private javax.swing.JLabel LabelPilihJenisKamar;
    private javax.swing.JTable Tabel;
    private javax.swing.JButton btnInfoKamar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisKamar;
    private javax.swing.JTextField inputDiagnosis;
    private javax.swing.JTextField inputGejala;
    private javax.swing.JTextField inputIDPasien;
    private javax.swing.JTextField inputObat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
