/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coba;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class InfoDokter extends javax.swing.JFrame {

    String s;

    /**
     * Creates new form InfoDokter
     */
    public InfoDokter() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUbah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        inputNama = new javax.swing.JTextField();
        inputUsia = new javax.swing.JTextField();
        cbJK = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        inputAlamat = new javax.swing.JTextField();
        inputKontak = new javax.swing.JTextField();
        inputTglJoin = new javax.swing.JTextField();
        cbGoldar = new javax.swing.JComboBox<>();
        inputSpesialisasi = new javax.swing.JTextField();
        inputJadwalPraktik = new javax.swing.JTextField();
        inputIDDokter = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(51, 153, 255));
        btnUbah.setText("Ubah Data");
        btnUbah.setMaximumSize(new java.awt.Dimension(140, 50));
        btnUbah.setMinimumSize(new java.awt.Dimension(140, 50));
        btnUbah.setPreferredSize(new java.awt.Dimension(140, 50));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 180, 50));

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(51, 153, 255));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/Back Button.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 170, 60));

        inputNama.setBackground(new java.awt.Color(255, 255, 255));
        inputNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputNama.setForeground(new java.awt.Color(0, 0, 0));
        inputNama.setBorder(null);
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 200, 200, 30));

        inputUsia.setBackground(new java.awt.Color(255, 255, 255));
        inputUsia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputUsia.setForeground(new java.awt.Color(0, 0, 0));
        inputUsia.setBorder(null);
        getContentPane().add(inputUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 240, 190, 30));

        cbJK.setBackground(new java.awt.Color(255, 255, 255));
        cbJK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbJK.setForeground(new java.awt.Color(51, 153, 255));
        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki-laki", "Perempuan" }));
        getContentPane().add(cbJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, -1));

        cbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cbStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(51, 153, 255));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Hubungan", "Belum Menikah", "Menikah", "Cerai" }));
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        inputAlamat.setBackground(new java.awt.Color(255, 255, 255));
        inputAlamat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputAlamat.setForeground(new java.awt.Color(0, 0, 0));
        inputAlamat.setToolTipText("");
        inputAlamat.setBorder(null);
        getContentPane().add(inputAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 200, 30));

        inputKontak.setBackground(new java.awt.Color(255, 255, 255));
        inputKontak.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputKontak.setForeground(new java.awt.Color(0, 0, 0));
        inputKontak.setBorder(null);
        getContentPane().add(inputKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 200, 30));

        inputTglJoin.setBackground(new java.awt.Color(255, 255, 255));
        inputTglJoin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputTglJoin.setForeground(new java.awt.Color(0, 0, 0));
        inputTglJoin.setBorder(null);
        getContentPane().add(inputTglJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 189, 30));

        cbGoldar.setBackground(new java.awt.Color(255, 255, 255));
        cbGoldar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbGoldar.setForeground(new java.awt.Color(51, 153, 255));
        cbGoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Golongan Darah", "A", "AB", "O", "B" }));
        getContentPane().add(cbGoldar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 200, -1));

        inputSpesialisasi.setBackground(new java.awt.Color(255, 255, 255));
        inputSpesialisasi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputSpesialisasi.setForeground(new java.awt.Color(0, 0, 0));
        inputSpesialisasi.setBorder(null);
        getContentPane().add(inputSpesialisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 189, 30));

        inputJadwalPraktik.setBackground(new java.awt.Color(255, 255, 255));
        inputJadwalPraktik.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputJadwalPraktik.setForeground(new java.awt.Color(0, 0, 0));
        inputJadwalPraktik.setBorder(null);
        getContentPane().add(inputJadwalPraktik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 200, 30));

        inputIDDokter.setBackground(new java.awt.Color(255, 255, 255));
        inputIDDokter.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        inputIDDokter.setForeground(new java.awt.Color(0, 0, 0));
        inputIDDokter.setBorder(null);
        getContentPane().add(inputIDDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 290, 30));

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(51, 153, 255));
        btnHapus.setText("Hapus Data");
        btnHapus.setMaximumSize(new java.awt.Dimension(140, 50));
        btnHapus.setMinimumSize(new java.awt.Dimension(140, 50));
        btnHapus.setPreferredSize(new java.awt.Dimension(140, 50));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 170, 50));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1200, 190));

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCari.setForeground(new java.awt.Color(51, 153, 255));
        btnCari.setText("Cari");
        btnCari.setBorder(null);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 167, 60, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/DataDokter.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTableData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM rumahsakit.datadokter");
            ResultSet rs = pst.executeQuery();
            Tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal!");
        }
    }
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
            PreparedStatement pst = conn.prepareStatement("Update datadokter set ID_Dokter= ?, Nama=?, Usia=?, Jenis_Kelamin=?, Status_Hubungan=?, Alamat=?, Telp=?, Golongan_Darah=?, Tanggal_Bergabung=?, Spesialisasi=?, Waktu_Praktik=? where ID_Dokter=?");

            pst.setString(1, inputIDDokter.getText());
            pst.setString(2, inputNama.getText());
            pst.setString(3, inputUsia.getText());
            pst.setString(4, (String) cbJK.getSelectedItem());
            pst.setString(5, (String) cbStatus.getSelectedItem());
            pst.setString(6, inputAlamat.getText());
            pst.setString(7, inputKontak.getText());
            pst.setString(8, (String) cbGoldar.getSelectedItem());
            pst.setString(9, inputTglJoin.getText());
            pst.setString(10, inputSpesialisasi.getText());
            pst.setString(11, inputJadwalPraktik.getText());
            pst.setString(12, inputIDDokter.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah diubah!");

            inputIDDokter.setText(null);
            inputNama.setText(null);
            inputUsia.setText(null);
            cbJK.setSelectedIndex(0);
            cbStatus.setSelectedIndex(0);
            inputAlamat.setText(null);
            inputKontak.setText(null);
            cbGoldar.setSelectedIndex(0);
            inputTglJoin.setText(null);
            inputSpesialisasi.setText(null);
            inputJadwalPraktik.setText(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukkan data sesuai format!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeAdmin admin = new HomeAdmin();
        admin.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
            PreparedStatement pst = conn.prepareStatement("Delete from datadokter where ID_Dokter = '" + inputIDDokter.getText() + "'");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data telah dihapus!");

            inputIDDokter.setText(null);
            inputNama.setText(null);
            inputUsia.setText(null);
            cbJK.setSelectedIndex(0);
            cbStatus.setSelectedIndex(0);
            inputAlamat.setText(null);
            inputKontak.setText(null);
            cbGoldar.setSelectedIndex(0);
            inputTglJoin.setText(null);
            inputSpesialisasi.setText(null);
            inputJadwalPraktik.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukkan data sesuai format!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int SelectedRow = Tabel.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) Tabel.getModel();
        inputIDDokter.setText(table.getValueAt(SelectedRow, 0).toString());
        inputNama.setText(table.getValueAt(SelectedRow, 1).toString());
        inputUsia.setText(table.getValueAt(SelectedRow, 2).toString());
        cbJK.setSelectedItem(table.getValueAt(SelectedRow, 3).toString());
        cbStatus.setSelectedItem(table.getValueAt(SelectedRow, 4).toString());
        inputAlamat.setText(table.getValueAt(SelectedRow, 5).toString());
        inputKontak.setText(table.getValueAt(SelectedRow, 6).toString());
        cbGoldar.setSelectedItem(table.getValueAt(SelectedRow, 7).toString());
        inputTglJoin.setText(table.getValueAt(SelectedRow, 8).toString());
        inputSpesialisasi.setText(table.getValueAt(SelectedRow, 9).toString());
        inputJadwalPraktik.setText(table.getValueAt(SelectedRow, 10).toString());
    }//GEN-LAST:event_TabelMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        try {
            String idDokter = inputIDDokter.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/rumahsakit", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM datadokter where ID_Dokter = '" + idDokter + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String Nama = rs.getString("Nama");
                inputNama.setText(Nama);
                String Usia = rs.getString("Usia");
                inputUsia.setText(Usia);
                String jk = rs.getString("Jenis_Kelamin");
                cbJK.setSelectedItem(jk);
                String sh = rs.getString("Status_Hubungan");
                cbStatus.setSelectedItem(sh);
                String Alamat = rs.getString("Alamat");
                inputAlamat.setText(Alamat);
                String Kontak = rs.getString("Telp");
                inputKontak.setText(Kontak);
                String goldar = rs.getString("Golongan_Darah");
                cbGoldar.setSelectedItem(goldar);
                String Join = rs.getString("Tanggal_Bergabung");
                inputTglJoin.setText(Join);
                String sp = rs.getString("Spesialisasi");
                inputSpesialisasi.setText(sp);
                String jp = rs.getString("Waktu_Praktik");
                inputJadwalPraktik.setText(jp);
            } else {
                JOptionPane.showMessageDialog(null, "ID tidak ditemukan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukkan data sesuai format!");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbGoldar;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputIDDokter;
    private javax.swing.JTextField inputJadwalPraktik;
    private javax.swing.JTextField inputKontak;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputSpesialisasi;
    private javax.swing.JTextField inputTglJoin;
    private javax.swing.JTextField inputUsia;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
