/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coba;

/**
 *
 * @author User
 */
public class InfoKamar extends javax.swing.JFrame {

    /**
     * Creates new form InfoKamar
     */
    public InfoKamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnKembali1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnKembali2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FASILITAS KAMAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 60));

        btnKembali1.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembali1.setForeground(new java.awt.Color(51, 102, 255));
        btnKembali1.setText("Catatan Pasien");
        btnKembali1.setMaximumSize(new java.awt.Dimension(158, 60));
        btnKembali1.setMinimumSize(new java.awt.Dimension(158, 60));
        btnKembali1.setPreferredSize(new java.awt.Dimension(158, 60));
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 620, 160, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 60));

        btnKembali2.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembali2.setForeground(new java.awt.Color(51, 102, 255));
        btnKembali2.setText("Menu Home");
        btnKembali2.setMaximumSize(new java.awt.Dimension(158, 60));
        btnKembali2.setMinimumSize(new java.awt.Dimension(158, 60));
        btnKembali2.setPreferredSize(new java.awt.Dimension(158, 60));
        btnKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 140, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coba/FasilitasKamar.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CatatanPasien catatan = new CatatanPasien();
        catatan.setVisible(true);
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembali2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
